name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  ci:
    name: pgwasm CI (fmt, clippy, test, pgrx test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: ./.github/actions/setup-pgrx-pg17

      - uses: ./.github/actions/install-wasm

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --workspace -- -D warnings

      - name: cargo test
        run: cargo test --workspace

      - name: cargo pgrx test
        run: cargo pgrx test pg17 -p pgwasm

      - name: cargo pgrx regress
        run: cargo pgrx regress pg17 --resetdb -p pgwasm
